captcha:
  img-height: 80
  img-width: 240
  key-long: 4
casbin:
  model-path: ./resource/rbac_model.conf
email:
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  nickname: test
  port: 465
  secret: xxx
  to: xxx@qq.com
excel:
  dir: ""
jwt:
  buffer-time: 86400
  expires-time: 604800
  signing-key: Driving
local:
  path: uploads/file
music:
  length: 50
  list-id: "3779629"
mysql:
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: Driving_School
  log-mode: true
  log-zap: ""
  max-idle-conns: 10
  max-open-conns: 10
  password: root
  path: 127.0.0.1:3306
  username: root
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
system:
  addr: 8888
  db-type: mysql
  env: public
  oss-type: local
  use-multipoint: true
weather:
  lang: zh_cn
  lat: "23.4155"
  log: "113.0968"
  units: metric
zap:
  director: log
  encode-level: LowercaseLevelEncoder
  format: console
  level: info
  link-name: latest_log
  log-in-console: true
  prefix: '[Driving-School]'
  showline: true
  stacktrace-key: stacktrace
